version: 2
jobs:
  build:
    working_directory: ~/sample-feedreader-rails
    docker:
      - image: circleci/ruby:2.5.0-node
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_DB: feedreader-rails_test
          POSTGRES_USER: postgres
          POSTGERS_PASSWORD:
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
      RAILS_ENV: test
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - sample-feedreader-rails-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - sample-feedreader-rails-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: sample-feedreader-rails-{{ checksum "Gemfile.lock" }}
      # Database setup
      - run: cp config/database.ci.yml config/database.yml
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # run tests!
      - run: bundle exec rake
