version: 2
jobs:
  build:
    parallelism: 3
    working_directory: /sample-feedreader-rails
    docker:
      - image: ruby:2.5.0
      - image: psql:9.6.5
        environment:
          POSTGRES_USER: sample-feedreader-rails
          POSTGRES_DB: sample-feedreader-rails_test
    environment:
      TZ: /usr/share/zoneinfo/Asia/Tokyo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - sample-feedreader-rails-{{ checksum "Gemfile.lock" }}
          # fallback to using the latest cache if no exact match is found
          - sample-feedreader-rails-
      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          paths:
            - ./vendor/bundle
          key: sample-feedreader-rails-{{ checksum "Gemfile.lock" }}
      # Database setup
      - run: bundle exec rake db:create
      - run: bundle exec rake db:schema:load
      # run tests!
      - run:
          name: run tests
          command: |
            mkdir /tmp/test-results
            TEST_FILES="$(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)"
